### ISSUE TITLE
마크다운 에디터 기능

### ISSUE THREAD

**Issue by kti0940** [tunEmvegnomb/gomunity#104]

**Comment by kimheejeong3808** [comment]
# Toast UI Editor Image Upload

---

# 목차

# 개발 레퍼런스

[[Base 64] Base64이란 무엇일까? / Base64 사용 이유와 인코딩과 디코딩](https://devuna.tistory.com/41)

[](https://nhn.github.io/tui.editor/latest/ToastUIEditorCore#addHook)

[Blob(블랍) 이해하기](https://heropy.blog/2019/02/28/blob/)

# 🎯 Toast UI Editor로 이미지 업로드를?!

---

![거북이반 커뮤니티, 거뮤니티 디테일 페이지 - Chrome 2022-08-10 오전 12_22_52 (2).png](Toast%20UI%20Editor%20Image%20Upload%207f56260e08b64028800bb26fe0a9f79f/%25EA%25B1%25B0%25EB%25B6%2581%25EC%259D%25B4%25EB%25B0%2598_%25EC%25BB%25A4%25EB%25AE%25A4%25EB%258B%2588%25ED%258B%25B0_%25EA%25B1%25B0%25EB%25AE%25A4%25EB%258B%2588%25ED%258B%25B0_%25EB%2594%2594%25ED%2585%258C%25EC%259D%25BC_%25ED%258E%2598%25EC%259D%25B4%25EC%25A7%2580_-_Chrome_2022-08-10_%25EC%2598%25A4%25EC%25A0%2584_12_22_52_(2).png)

- 마크다운 작성을 지원하는 편집기 Toast UI Editor는 이미지 업로드를 다양한 방식으로 지원한다.
- 그러나 input 파일형태가 아닌 Toast UI 편집기에서 업로드를 진행하면 **base64** 형태로 코드가 그대로 편집기의 내용으로 들어오게 된다!
- 이 텍스트를 그대로 저장하는 것은 아무래도 좋은 선택은 아니다!

# 🤔 Base64?

- 구글링한 결과, 위키피디아에서는 다음과 같다고 한다.

[컴퓨터 프로그래밍](https://en.wikipedia.org/wiki/Computer_programming) 에서 **Base64** 는 4개의 6비트 Base64 숫자로 나타낼 수 있는 24비트 시퀀스로 [이진 데이터 (보다 구체적으로 8비트 바이트 시퀀스)를 나타내는 이진](https://en.wikipedia.org/wiki/Binary_data) [-텍스트 인코딩](https://en.wikipedia.org/wiki/Binary-to-text_encoding) 체계 의 그룹입니다 .

모든 바이너리-텍스트 인코딩 방식에 공통적인 Base64는 텍스트 콘텐츠만 안정적으로 지원하는 채널에서 바이너리 형식으로 저장된 데이터를 전달하도록 설계되었습니다. [Base64는 HTML](https://en.wikipedia.org/wiki/HTML) 및 [CSS](https://en.wikipedia.org/wiki/CSS) 파일과 같은 텍스트 자산 내부 에 [이미지 파일](https://en.wikipedia.org/wiki/Image_files) 또는 기타 바이너리 자산 을 포함하는 기능인 [World Wide Web](https://en.wikipedia.org/wiki/World_Wide_Web) [[1]](https://en.wikipedia.org/wiki/Base64#cite_note-1) 에서 특히 널리 사용 됩니다. [[2]](https://en.wikipedia.org/wiki/Base64#cite_note-2)

Base64는 또한 전자 메일 첨부 파일을 보내는 데 널리 사용됩니다. 이것은 원래 형식의 [SMTP 가 7비트 ASCII 문자만 전송하도록 설계되었기 때문에 필요합니다.](https://en.wikipedia.org/wiki/Simple_Mail_Transfer_Protocol) 이 인코딩으로 인해 33-37%의 오버헤드가 발생합니다(인코딩 자체의 경우 33%, 삽입된 줄 바꿈으로 인해 최대 4% 증가).

- 즉, **웹에서 이미지를 인코딩하는 방식**이라는 것이다!
- 결국, 이미지를 업로드 하는 과정에서 이 긴 인코딩 데이터는 파일 형식이 아닌 특수한 형태로 저장되기 때문에 **base64를 다루는 코드가 따로 필요**하다!

# ✍ 사용법

## 💡 editor.addHook

- [Toast UI Editor 공식문서](https://www.notion.so/Toast-UI-Editor-Image-Upload-2cd71623c843457d8472ec075f43e835)에 의하면, `editor.addHook` 이라는 toastui 라이브러리 메서드에 의해서 base64로 인코딩되는 이미지를 **에디터 컨텐츠에 그대로 작성하기 전에, 낚아챌 수 있다!**
- 파일을 인코딩 해서 텍스트에 붙이기 전에 코드를 통해서 어떤 작업을 취할 수 있는 **중간 역할**을 수행할 수 있게 된다.
- 이 문서에서는 `editor.addHook` 메서드를 통해서, 파일을 인코딩해 텍스트에 적기 전에 **AWS S3에 파일을 업로드 한 뒤에, 그 URL링크를 돌려주어 컨텐츠에 상대적으로 매우 짧은 URL만을 남길 것**이다!
- `editor.addHook`은 두 가지의 인자인 `type`과 `handler`를 받는다.
    - `type`은 string 형식으로, 이벤트 타입을 이야기한다. 이 문서에서는 `addImageBlobHook` 을 사용한다.
    - `handler`는 function 형식으로, 이벤트 함수를 이야기한다. 이 함수에서 중간과정의 코드가 들어간다.

## 💡 addImageBlobHook

- `addImageBlobHook`은 위에서 설명한 base64로 인코딩된 Blob이라는 녀석을 낚아채는 함수로, 실제 코드에서는 `editor.addHook`의 첫 번째 인자인 type으로만 작성한다.

## 💡 handler function

- `addHook`의 두 번째 인자인 `handler`는 함수로 작성하며, 이름을 작성하지 않는 **anonymous function**으로 작성한다(함수 자체를 재사용할 일이 없기 때문!)
- 함수는 이 후 받아올 데이터가 await를 필요로 하기에 **async funtion**을 사용한다.
- 함수에는 `blob`과 `callback`을 인자로 요구한다.
    - `blob`은 낚아챌 **파일**이다
    - `callback`은 낚아챈 녀석을 바꿔줄 **URL**이다

## 💡 blob

- Blob은 [구글링한 블로그](https://www.notion.so/Toast-UI-Editor-Image-Upload-2cd71623c843457d8472ec075f43e835)에 의하면, 아래와 같은 정의를 가지고 있다.

JavaScript에서 Blob(Binary Large Object, 블랍)은 이미지, 사운드, 비디오와 같은 멀티미디어 데이터를 다룰 때 사용할 수 있습니다.

대개 데이터의 크기(Byte) 및 MIME 타입을 알아내거나, 데이터를 송수신을 위한 작은 Blob 객체로 나누는 등의 작업에 사용합니다.

- 즉, **base64가 이미지를 인코딩하는 방식**이라면, **blob은 그 파일 오브젝트를** 의미한다
- 인코딩한 데이터 텍스트 말고, 파일 자체를 원하기에 blob을 취한다고 생각하자
- `handler function`에 들어간 인자 만으로 **바로 사용해서 취할 수 있게 된다**. `console.log`로 확인해보자

## 💡 callback

- `callback`은 중간과정에서 `blob`으로 처리한 뒤에 URL을 적어 에디터에 길었던 base64 코드 대신 주소만 남겨줄 수 있게 하는 마지막 **마감의 역할**을 하는 함수이다.
- `callback(실제로 들어갈 주소값, “링크를 숨길 값 이름”)` 형태로 작성하게 된다.

## 💡 S3 Upload

- 블랍으로 낚아낸 이미지 파일을 그대로 백엔드로 보내 이미지를 바로 S3에 업로드를 시키고 URL을 돌려줄 VIEW를 작성한다.
    - 백엔드로 보낼 Javascript Fetch API가 필요하다
    - `Boto3`를 활용한 S3 업로드 함수 및 `AWS CLI`(혹은 AWS 시크릿키)가 필요하다
    - 이 문서는 이미 AWS CLI 설정 및 S3 세팅이 되어 있는 상태를 전제로 한다.

# 👨‍💻 코드

### editor.addHook

- 주의점으로는 스크립트의 순서가 중요하다는 것이다
- editor라고 선언된 **Toast UI Editor 편집기 스크립트** 보다 아래 코드가 밑에 있어야 작동한다
- 그렇지 않다면, `editor is not defined` 라는 에러코드를 마주할 것이다.

```jsx
// editor를 이미 HTML에 선언해두었어야 함
// 이 코드는 editor가 존재하는 스크립트보다 밑에 있어야함

editor.addHook("addImageBlobHook", async function (blob, callback) {
    console.log("블랍", blob);

		// 이미지 업로드를 위해 담아둘 형식
    const formdata = new FormData();
    formdata.append("file", blob);
    
		// fetch API로 폼데이터를 담아 호출, URL로 돌아올 값을 변수 저장
    const response_json = await editorImageUpload(formdata);

    // 콜백으로 긴 코드를 짧게, 목적에 맞게 변환
    callback(response_json.url, "image");
});
```

### fetch API

```jsx
// 블랍 이미지 업로드
async function editorImageUpload(formdata) {
    const response = await fetch(`${deploy_base_url}/qna/upload/`, {
        method: "POST",
        headers:{
            Authorization: "Bearer " + localStorage.getItem("access"),
        },
        body: formdata,
    });
    const response_json = await response.json();
    return response_json;
}
```

### Django S3 Upload

```python
def upload_s3(image, user):
    s3 = boto3.client('s3')
    
    now = datetime.datetime.now()
    now = now.strftime('%Y%m%d_%H%M%S')
    key = f"media/{user}/{now}.jpg"
    print(f"키는 ->{key}")
    print(f"유저는 ->{user}")
    try:
        s3.put_object(
            ACL="public-read",
            Bucket = 'gomunity.shop',
            Body=image,
            Key=key,
            ContentType=image.content_type
            )
        url = f"https://gomunity.shop.s3.ap-northeast-2.amazonaws.com/{key}"
        return url
    except Exception as e:
        print("오류발생")
        print(e)
```
